/* Global imports */
import type { Metadata } from "next";
import { Poppins } from "next/font/google";
/* Scoped imports */
/* Local imports */
import "./globals.css";

const poppins = Poppins({ subsets: ["latin"], weight: "500" });

export const metadata: Metadata = {
  title: "TexTwo",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={poppins.className + " bg-gray-200"}>{children}</body>
    </html>
  );
}
